name: sftp-upload

on:
  push:
    branches: [staging,main]
      
jobs:
  deploy:
    name: Deploy code on Every push
    runs-on: ubuntu-latest
    steps:
      - name: Get Lates code
        uses: actions/checkout@v1
        with:
          ref: ${{github.ref_name}}

      - name: List output files
        run: ls

      - name: Set remote for live
        run: |
          REMOTE_SRV_PATH=/home/git_dep_test/main_folder/
          echo "$REMOTE_SRV_PATH"
        if: ${{ github.ref_name == 'main'}}

      - name: Set remote for staging
        run: |
          REMOTE_SRV_PATH=/home/git_dep_test/staging_folder/
          echo "$REMOTE_SRV_PATH"
        if: ${{ github.ref_name == 'staging'}}

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          run: |
            remote_path: $REMOTE_SRV_PATH
          sftp_only: true
