on:
  push:
    branches:    
      - main
      
jobs:
  omni-pro-log-handler:
    name: SFTP-File-Upload
    runs-on: ubuntu-latest
    steps:
    - name: List output files
      run: ls

    - uses: actions/checkout@main

    - name: omni-pro-log-handler
      uses: AnushkaKRajasingha/omni-pro-log-handler@main
      env:
        FTP_SERVER: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: ${{ secrets.FTP_REMOTE_PATH }}
        METHOD: sftp
        PORT: 22
