name: sftp-upload

on:
  push:
    branches: [main]
      
jobs:
  deploy:
    name: Deploy code on Every push
    runs-on: ubuntu-latest
    steps:
      - name: Get Lates code
        uses: actions/checkout@main

      - name: List output files
        run: ls

      - name: Upload files
        uses: AnushkaKRajasingha/omni-pro-log-handler@main
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /home/git_dep_test/
          protocol: ftps
