name: sftp-upload

on:
  push:
    branches: [main]
      
jobs:
  deploy:
    name: Deploy code on Every push
    runs-on: ubuntu-latest
    steps:
      - name: Get Lates code
        uses: actions/checkout@main

      - name: List output files
        run: ls

      - name: Upload files
        uses: ./
        with:
          FTP_SERVER: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: ${{ secrets.FTP_REMOTE_PATH }}
          METHOD: sftp
